runtime: nodejs
env: flex
service: matching-service
network:
  session_affinity: true
env_variables:
  ENV: $ENV
  DB_CLOUD_URI: $DB_CLOUD_URI
  REDIS_CLOUD_URI: $REDIS_CLOUD_URI
  REDIS_CLOUD_PORT: $REDIS_CLOUD_PORT
  REDIS_CLOUD_PASSWORD: $REDIS_CLOUD_PASSWORD
  JWT_SECRET: $JWT_SECRET
