export const STATUS_CODE_CREATED = 201;
export const STATUS_CODE_CONFLICT = 409;
export const STATUS_CODE_LOGGED_IN = 200;
export const STATUS_CODE_LOGIN_FAILED = 401;
export const STATUS_CODE_LOGGED_OUT = 200;
export const STATUS_CODE_LOG_OUT_FAILED = 401;
export const STATUS_CODE_DELETED = 200;
export const STATUS_CODE_SUCCESS = 200;
