name: Deploy Dispatch Settings

on:
  push:
    branches: [ main ]
    paths: 
      - 'backend/dispatch.yaml'
      - '.github/workflows/dispatch.yaml'

env:
  PROJECT_ID: cs3219-g55
  REGION: asia-southeast1

jobs:
  deploy:
    name: Dispatch-Settings 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Google Auth
      id: auth
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: ${{ secrets.GCP_GAE_CREDENTIALS }}

    - id: 'deploy'
      name: 'deploy to gae'
      uses: 'google-github-actions/deploy-appengine@v0'
      with:
        deliverables: 'backend/dispatch.yaml'
