name: Deploy to Cloud Run from Source

on:
  push:
    branches: [ dockerize-user-service ]

env:
  PROJECT_ID: cs3219-g55
  REGION: asia-southeast1

jobs:
    deploy:
        name: Deploy user-service
        runs-on: ubuntu-latest
        env:
          SERVICE: user-service
        steps:

        - name: Login
          uses: google-github-actions/setup-gcloud@v0
          with:
            project_id: ${{ env.PROJECT_ID }}
            service_account_email: ${{ env.SERVICE }}@${{ env.PROJECT_ID }}.iam.gserviceaccount.com
            service_account_key: ${{ secrets.GCP_CREDENTIALS }}

        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Google Auth
          id: auth
          uses: 'google-github-actions/auth@v0'
          with:
            credentials_json: ${{ secrets.GCP_CREDENTIALS }}

        - name: Deploy to Cloud Run
          id: deploy
          uses: google-github-actions/deploy-cloudrun@v0
          with:
            service: ${{ env.SERVICE }}
            region: ${{ env.REGION }}
            source: ./${{ env.SERVICE }}
            env_vars: |
              ENV=PROD
              DB_CLOUD_URI=${{ secrets.DB_CLOUD_URI }}
              REDIS_CLOUD_URI=${{ secrets.REDIS_CLOUD_URI }}
              REDIS_CLOUD_PORT=${{ secrets.REDIS_CLOUD_PORT }}
              REDIS_CLOUD_PASSWORD=${{ secrets.REDIS_CLOUD_PASSWORD }}
              JWT_SECRET=${{ secrets.JWT_SECRET }}
        
          - name: Show Output
            run: echo ${{ steps.deploy.outputs.url }}
