name: Cloud Run Deploy Matching-Service

on:
  push:
    branches: [ main, deploy-tests ]
    path: 
      - 'matching-service/**'
      - '.github/workflows/matching.yml'

env:
  PROJECT_ID: cs3219-g55
  REGION: asia-southeast1
  SERVICE: matching-service

jobs:
    deploy_2:
        name: Matching-Service
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Use Node.js
          uses: actions/setup-node@v3
          with:
            node-version: '14.x'

        - name: Install dependencies
          working-directory: ${{ env.SERVICE }}
          run: npm install
        - name: Run CI tests
          working-directory: ${{ env.SERVICE }}
          run: npm run test
          env:
            ENV: test
            DB_CLOUD_URI: ${{ secrets.DB_CLOUD_URI }}

        - name: Google Auth
          id: auth
          uses: 'google-github-actions/auth@v0'
          with:
            credentials_json: ${{ secrets.GCP_CREDENTIALS }}

        - name: Deploy to Cloud Run
          id: deploy
          uses: google-github-actions/deploy-cloudrun@v0
          with:
            service: ${{ env.SERVICE }}
            region: ${{ env.REGION }}
            source: ./${{ env.SERVICE }}
            env_vars: |
              ENV=PROD
              DB_CLOUD_URI=${{ secrets.DB_CLOUD_URI }}
        
        - name: Show Output
          run: echo ${{ steps.deploy.outputs.url }}
