name: Question Service Deploy

on:
  push:
    branches: [ main ]
    paths: 
      - 'backend/question-service/**'
      - '.github/workflows/question-service.yaml'

env:
  PROJECT_ID: cs3219-g55
  REGION: asia-southeast1
  SERVICE_NAME: question-service

jobs:
  deploy:
    name: Question-Service
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Google Auth
      id: auth
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: ${{ secrets.GCP_GAE_CREDENTIALS }}

    # A plugin that helps to push github secrets into the GAE service -
    # the google-github-actions/deploy-appengine plugin does not support env vars.
    - name: GCP app engine yaml compiler
      uses: gokiwibot/gcp-yaml-compiler@v1.0
      with:
        file: ./backend/${{ env.SERVICE_NAME }}/app.yaml
      env:
        ENV: PROD
        DB_CLOUD_URI: ${{ secrets.DB_CLOUD_URI }}
        REDIS_CLOUD_URI: ${{ secrets.REDIS_CLOUD_URI }}
        REDIS_CLOUD_PORT: ${{ secrets.REDIS_CLOUD_PORT }}
        REDIS_CLOUD_PASSWORD: ${{ secrets.REDIS_CLOUD_PASSWORD }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}

    - id: 'deploy'
      name: 'deploy to gae'
      uses: 'google-github-actions/deploy-appengine@v0'
      with:
        deliverables: 'backend/${{ env.SERVICE_NAME}}/app.yaml'

    - name: 'show output'
      run: 'echo ${{ steps.deploy.outputs.url }}'